### ISSUE TITLE
Added to the fisherman index

### ISSUE THREAD

**Issue by ghost** [Shadowigor/plugin-errno-grep#1]
hey! are you familiar with fisherman? It's a fish-shell plugin manager that can run both omf plugins and [fishery](https://github.com/fishery) plugins, plus other features.

I already added errno-grep to the index, so you can now:

```
fisher i errno-grep
```

Cheers.

EDIT: btw there is a nice summary here http://why.fisherman.sh comparing fisherman with ohmyfish

**Comment by Shadowigor** [comment]
Nice, thanks! I'll take a look at it, it looks very promising.

**Comment by ghost** [comment]
Sure, thanks for contributing to the fish ecosystem.
